./gameboy BROKER CAUGHT_POKEMON 1 OK
./gameboy BROKER CAUGHT_POKEMON 0 FAIL

./gameboy BROKER CATCH_POKEMON Pikachu 2 3
./gameboy BROKER CATCH_POKEMON Squirtle 5 2

./gameboy BROKER NEW_POKEMON Onyx 4 5 5

./gameboy SUSCRIPTOR CAUGHT_POKEMON 10

./gameboy BROKER NEW_POKEMON Vaporeon 4 5 2
