./gameboy GAMECARD NEW_POKEMON Jolteon 2 2 1 0
./gameboy GAMECARD NEW_POKEMON Flareon 4 6 1 1
./gameboy GAMECARD NEW_POKEMON Umbreon 10 6 1 2
./gameboy GAMECARD NEW_POKEMON Espeon 7 1 1 3
./gameboy GAMECARD NEW_POKEMON Vaporeon 4 10 1 4
./gameboy GAMECARD NEW_POKEMON Jolteon 2 1 1 6
./gameboy GAMECARD NEW_POKEMON Flareon 4 2 1 5
./gameboy GAMECARD NEW_POKEMON Umbreon 10 5 1 7
./gameboy GAMECARD NEW_POKEMON Espeon 7 2 1 8
./gameboy GAMECARD NEW_POKEMON Vaporeon 4 9 1 9
