./gameboy BROKER APPEARED_POKEMON Onix 2 8 1 4
./gameboy BROKER APPEARED_POKEMON Gengar 6 6 1 5
./gameboy BROKER APPEARED_POKEMON Squirtle 5 5 1 6

./gameboy BROKER APPEARED_POKEMON Umbreon 10 6 1 7
./gameboy BROKER APPEARED_POKEMON Espeon 7 1 1 8
./gameboy BROKER APPEARED_POKEMON Vaporeon 4 10 1 9